### ISSUE TITLE
Pesquisa e Paginação em JSON ?

### ISSUE THREAD

**Issue by juniorsatanas** [loiane/angular2-crud-rest#1]
Loiane,  estou fazendo todos os projetos do http://loiane.training/, já aprendi muito Obrigado !
Eu estou com uma dúvida neste projeto, como fazer uma pesquisa tipo esta :+1: 
 Tour of Heroes:
http://embed.plnkr.co/71VEirn2WzveVVMuHGp5/

Você tem algum projeto que faça pesquisa em WebService passando um valor como parâmetro e atualize o  resultado na gride ? com essa grid paginada ?

tipo isto:
`<code>`
## 	**buscarPorNome(nome: string): Observable<Leitor> {

		return this.http.get(this.httpUtilLeitor.urlbuscarPorId(this.path + '/' + nome), 
						this.httpUtilLeitor.headers())
	                .map(this.httpUtilLeitor.extrairDados)
	                .catch(this.httpUtilLeitor.processarErros);
	}**

`</code>`

Obrigado !

**Comment by loiane** [comment]
Oi Junior, teria que fazer a paginação no servidor mesmo (é o mais comum). Dê uma olhada no ag-grid (tem pra ng 2 tb). []s

**Comment by juniorsatanas** [comment]
Obrigado meu amor !
